### ISSUE TITLE
关于 OptionalDto

### ISSUE THREAD

**Issue by wjw-gavin** [waitingsong/midway-components#143]
大佬有个问题，https://github.com/midwayjs/midway/discussions/3945#discussioncomment-10042637
当我传 [] 时，`CreateDTO` 的参数并没有追加到 `UpdateDTO` 中，只有我写了一个排除的属性，才会把剩余的追加到 `UpdateDTO` 并且可选

这是传空数组的
<img width="583" alt="image" src="https://github.com/user-attachments/assets/b39bc216-22c0-43a7-b5e9-6b597fd329ef">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/c1b19c8c-4068-4459-9625-c162b777716f">

这是传一个属性
<img width="614" alt="image" src="https://github.com/user-attachments/assets/ceb359bd-afc8-4a8a-97b0-53fcc4f13e59">
<img width="376" alt="image" src="https://github.com/user-attachments/assets/ab149516-4187-4811-94a4-ed2cf424e955">

**Comment by waitingsong** [comment]
给个 CreateDTO  的 demo

**Comment by waitingsong** [comment]
之所以第二个参数要留一个必选的空数组，是因为如果不传第二参数结果参数所有字段都没有 可选属性。看来 ts 5.2 以及老版本的类型体操还不够完美。

**Comment by wjw-gavin** [comment]
我是使用的 midway 来 init 的项目，看 ts 是 "typescript": "~4.8.4"，而且在使用上貌似也不兼容？[demo 仓库](https://github.com/wjw-gavin/midway-demo)

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/f7994f9f-45ea-4b70-9bb9-1d58495bef08">

**Comment by waitingsong** [comment]
不是 TS 版本问题，是 ESM 问题：你项目是 cjs， `@mwcp/share` 是纯 ESM 模块。 CJS 项目无法加载 ESM 模块（反过来是可以的）。

好在已经考虑到这个情况了，解决方法：
- 拷贝 [dto.util.ts](https://github.com/waitingsong/midway-components/blob/main/packages/share/src/util/dto.util.ts) 这个文件到你的项目
- 拷贝一下代码到上面的文件中并删除行首对该类型的导入
  ```ts
  export type TupleToUnion<T extends any[] | readonly any[]> = T[number]
  ```

**Comment by waitingsong** [comment]
[PR](https://github.com/wjw-gavin/midway-demo/pull/1) ESM 改造参考

**Comment by wjw-gavin** [comment]
> 不是 TS 版本问题，是 ESM 问题：你项目是 cjs， `@mwcp/share` 是纯 ESM 模块。 CJS 项目无法加载 ESM 模块（反过来是可以的）。
> 
> 好在已经考虑到这个情况了，解决方法：
> 
> * 拷贝 [dto.util.ts](https://github.com/waitingsong/midway-components/blob/main/packages/share/src/util/dto.util.ts) 这个文件到你的项目
> * 拷贝如下代码到上面的文件中并删除行首对该类型的导入
>   ```ts
>   export type TupleToUnion<T extends any[] | readonly any[]> = T[number]
>   ```
> 
> 另外，ESM 模块是趋势，建议所有模块、项目都逐步转向 ESM。 业务代码不需要变化，主要需要更改 package.json, tsocnofig.json 这两个配置文件

确实，不过按 midwayjs 教程初始化的项目是 cjs 的，这对新手来说很少去关注这块。不过 copy 一下源码也是一种方案

**Comment by waitingsong** [comment]
midwayjs 教程初始化可以选择 esm 的 “v3-esm”

**Comment by wjw-gavin** [comment]
> midwayjs 教程初始化可以选择 esm 的 “koa-v3-esm” https://midwayjs.org/docs/tool/create_midway#%E9%BB%98%E8%AE%A4%E8%A1%8C%E4%B8%BA

￣□￣｜｜，没注意到下面那个选项... 我的我的，感谢解答。
