### ISSUE TITLE
@mwcp/cache 报错

### ISSUE THREAD

**Issue by LBC000** [waitingsong/midway-components#70]
![image](https://github.com/waitingsong/midway-components/assets/33395246/c2a67367-c6e5-4174-9bae-e2437ee5ef77)
![image](https://github.com/waitingsong/midway-components/assets/33395246/e75d5d55-20a6-4345-9cd7-2421bbe1302d)

![image](https://github.com/waitingsong/midway-components/assets/33395246/ab9abf1d-dad1-4c9e-bef3-bcd2c714ccab)

/ Midway Starting Missing baseUrl in compilerOptions. tsconfig-paths will be skipped

/ Midway Starting
start error: ⨯ Unable to compile TypeScript:
src/config/config.local.ts(8,16): error TS2352: Conversion of type '{ keys: string; typeorm: { dataSource: { default: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; synchronize: true; logging: false; charset: string; cache: true; entityPrefix: string; entities: string[]; }; }; }; cache: { ...; }; customJwt: { ...; }; }' to type 'MidwayConfig' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ keys: string; typeorm: { dataSource: { default: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; synchronize: true; logging: false; charset: string; cache: true; entityPrefix: string; entities: string[]; }; }; }; cache: { ...; }; customJwt: { ...; }; }' is missing the following properties from type 'MidwayConfig': [ConfigKey.config], [ConfigKey.middlewareConfig], [ConfigKey.otlpGrpcExporterConfig], [ConfigKey.config], [ConfigKey.middlewareConfig]

src/config/config.local.ts(8,16): error TS2352: Conversion of type '{ keys: string; typeorm: { dataSource: { default: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; synchronize: true; logging: false; charset: string; cache: true; entityPrefix: string; entities: string[]; }; }; }; cache: { ...; }; customJwt: { ...; }; }' to type 'MidwayConfig' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '{ keys: string; typeorm: { dataSource: { default: { type: "mysql"; host: string; port: number; username: string; password: string; database: string; synchronize: true; logging: false; charset: string; cache: true; entityPrefix: string; entities: string[]; }; }; }; cache: { ...; }; customJwt: { ...; }; }' is missing the following properties from type 'MidwayConfig': [ConfigKey.config], [ConfigKey.middlewareConfig], [ConfigKey.otlpGrpcExporterConfig], [ConfigKey.config], [ConfigKey.middlewareConfig]

**Comment by waitingsong** [comment]
tsconfig.ts 设置 baseUrl： ".' 看看？

**Comment by waitingsong** [comment]
另外，第二张图里面同时使用了具名导出 (`export const cacheConfig`) 和默认导出 (`export default {}`) 。应该避免这种情况。要么全部是具名，要么只有一个默认导出。

**Comment by waitingsong** [comment]
安装最新版试试
`npm i @mwcp/cache@^11.3.5`
